name: Update NPM Dependencies
description: Checks if there are updates to NPM packages, and creates a PR with the updated package*.json files
inputs: 
  base-branch: 
    description: The branch used as the base for the dependency update checks
    default: main
  target-branch: 
    description: The branch where the PR will be created
    default: update-dependencies
  working-directory: 
    description: The working directory where the package-lock.json file is located
    required: true
    default: .
  gh-token: 
    description: The GitHub token used to create the PR
    required: true
  debug: 
    description: Enable debug mode
    required: false
runs: 
  using: node20
  main: index.js
