name: workflow events
on:
  # push:
  # pull_request:
  # schedule:
  # every 15 minutes
  # - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger event
        run: |
          echo "Event name: ${{ github.event_name }}"
