name: using third-party actions
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Print folders
        run: ls -la
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Print node version
        run: node --version
      - name: Install dependencies
        run: |
          cd 04-using-actions
          npm install
      - name: Run tests
        run: |
          pwd
          cd 04-using-actions
          npm run test
