name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
      node-version:
        type: choice
        description: Node version
        options: ["18.x", "20.x", "22.x"]
        default: "Node version"

      use-cache:
        type: boolean
        default: true
        description: Whether to execute cache step
jobs:
  build:
    defaults:
      run:
        working-directory: 13-caching/react-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        with:
          path: 13-caching/react-app/node_modules
          key: node-modules-key-${{ hashFiles('13-caching/react-app/package-lock.json') }}
      - name: Install dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
