name: 14 - Working with Artifacts

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: 14-artifacts/react-app/node_modules
          key: 14-artifacts-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
      - name: Install dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci
      - name: Unit tests
        run: npm run test
      - name: Build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          path: 14-artifacts/react-app/build
          name: app
  deply:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: app
          path: build
      - name: Ls
        run: ls -laR
