name: 15 Working with matrices

on:
  workflow_dispatch:

jobs:
  compatibility:
    name: ${{matrix.os}} - ${{matrix.node}}
    # runs-on: ${{matrix.os}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x 20.x]
        os: [ubuntu-latest, windows-latest]
        include:
          - node: 16.x
            os: ubuntu-latest
          - tag: experimental
            node: 20.x
            os: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - name: Some tests
        run: echo "Running tests on ${{matrix.os}} ${{matrix.node}}"
