name: 17 - 1 - Custom Actions - Composite
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        options: [dev, prod]
run-name: 17 - 1 - Custom Actions - Composite | env - ${{inputs.target-env}}
env:
  working-directory: 17-custom-actions/react-app
jobs:
  build:
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-dir: ${{env.working-directory}}
          target-env: ${{inputs.target-env}}
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
