name: 17 - 2 - Custom Actions - JS
run-name: "17 - 2 - Custom Actions - javascript: ${{ inputs.debug }}, base-branch: ${{ inputs.base-branch }} target-branch: ${{ inputs.target-brach }} working-directory: ${{ inputs.working-directory }}"
on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: The branch used as the base for the dependency update checks
        default: main
      target-branch:
        description: The branch where the PR will be created
        default: update-dependencies
      working-directory:
        description: The working directory where the package-lock.json file is located
        required: true
        default: 17-custom-actions/react-app
      debug:
        description: Enable debug mode
        required: false
        default: "true"

env:
  working-directory: 17-custom-actions/react-app
jobs:
  update:
    # top-level permissions key with two parameters, contents and pull-requests, both set to write.
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Check for updates
        uses: ./.github/actions/js-dependency-update
        with:
          debug: ${{ inputs.debug }}
          base-branch: ${{ inputs.base-branch }}
          target-branch: ${{ inputs.target-branch }}
          working-directory: ${{ inputs.working-directory }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
