name: 17 - 1 - Custom Actions - JS
on:
  workflow_dispatch:
run-name: 17 - 2 - Custom Actions - javascript
env:
  working-directory: 17-custom-actions/react-app
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Check for updates
        uses: ./.github/actions/js-dependency-update
